apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    spec:
      containers:
        - name: test
          image: ubuntu:latest
          volumeMounts:
          - name: conf
            mountPath: /conf
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      volumes:
        - name: conf
          projected:
            sources:
            - configMap:
                name: bpapi-esb
            - configMap:
                name: card-list
    metadata:
      labels:
        app: website
      annotations:
        {{- toYaml .Values.secret | nindent 8 }}