apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    spec:
      serviceAccountName: internal-app
      containers:
        - name: test
          image: ubuntu:latest
          volumeMounts:
          - name: bpapiEsb
            mountPath: /conf/bpapiEsb.conf
            subPath: bpapiEsb.conf
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      volumes:
      - name: bpapiEsb
        configMap:
          name: bpapiEsb
          items:
            - key: bpapiEsb.conf
              path: bpapiEsb.conf
    metadata:
      labels:
        app: website
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- toYaml .Values.secret | nindent 8 }}