apiVersion: v1
kind: Service
metadata:
  name: smx
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: smx
  selector:
    app: test  